#port
server.port=8081

#log level statement: for debug statements
logging.level.org.springframework.web = debug
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.org.springframework.boot.context.properties=DEBUG
logging.level.org.springframework.core.env=DEBUG



#db properties - create a database postgresql
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
